version: '3'


networks:
  shared_network:

  
services:
  magic:
    command: mage start ${PROJECT_NAME}
    container_name: magic
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 6789:6789
    volumes:
      - .:/home/src/
    restart: on-failure:5
    networks:
      - shared_network