
version: 2

models:
  - name: spike_invasive_near_divesites
    config:
      materialized: table
    columns:
      - name: title
        description: The title of the dive site.
        tests:
          - not_null
      - name: observation_month
        description: The month of the invasive species occurrence.
        tests:
          - not_null
      - name: species
        description: The species of the invasive occurrence.
        tests:
          - not_null
      - name: total_invasive_individuals
        description: The total count of invasive individuals.
        tests:
          - not_null

  - name: spike_redlist_near_divesites
    config:
      materialized: table
    columns:
      - name: title
        description: The title of the dive site.
        tests:
          - not_null
      - name: observation_month
        description: The month of the redlist species occurrence.
        tests:
          - not_null
      - name: species
        description: The species of the redlist occurrence.
        tests:
          - not_null
      - name: total_redlist_individuals
        description: The total count of redlist individuals.
        tests:
          - not_null