
version: 2

sources:
    - name: staging

      database: gbif-412615
      schema: marine_data

      tables:
        - name: local_data


models:
  - name: stg_local_data
    description: "A starter dbt model"
    # columns:
    #   - name: id
    #     description: "The primary key for this table"
    #     tests:
    #       - unique
    #       - not_null