
version: 2

models:
  - name: stg_gbif_occurences
    columns:
      - name: species
        description: "The species of the occurrence. This field is required and must not be null."
        tests:
          - not_null
      - name: individualcount
        description: "Count of individuals for the species. This field is required and must not be null."
        tests:
          - not_null
      - name: geography
        description: "The geographical location of the occurrence. This field is required and must not be null."
        tests:
          - not_null
      - name: eventdate
        description: "The date of the occurrence. This field is required and must not be null."
        tests:
          - not_null
      - name: source
        description: "The source of the occurrence. This field is required and must not be null."
        tests:
          - not_null
          - allowed_values:
              values: ['GBIF']
  - name: stg_obis_occurences
    columns:
      - name: species
        description: "The species of the occurrence. This field is required and must not be null."
        tests:
          - not_null
      - name: individualcount
        description: "Count of individuals for the species. This field is required and must not be null."
        tests:
          - not_null
      - name: geography
        description: "The geographical location of the occurrence. This field is required and must not be null."
        tests:
          - not_null
      - name: eventdate
        description: "The date of the occurrence. This field is required and must not be null."
        tests:
          - not_null
          - allowed_values:
              values: ['OBIS']          
  - name: stg_reef_check_occurences
    columns:
      - name: species
        description: "The species of the occurrence. This field is required and must not be null."
        tests:
          - not_null
      - name: individualcount
        description: "Count of individuals for the species. This field is required and must not be null."
        tests:
          - not_null
      - name: geography
        description: "The geographical location of the occurrence. This field is required and must not be null."
        tests:
          - not_null
      - name: eventdate
        description: "The date of the occurrence. This field is required and must not be null."
        tests:
          - not_null
          - allowed_values:
              values: ['REEF_CHECK']    