
version: 2

models:
  - name: stg_gbif_occurences
    description: |
      GBIF (Global Biodiversity Information Facility) is an international network and research infrastructure that provides open access to biodiversity data. 
      It retrieves information about the species, individual count, event date, geographical location, and source from the `bigquery-public-data.gbif.occurrences` table. 
      The `geography` column is derived from the `decimallongitude` and `decimallatitude` columns using the `ST_GEOGPOINT` function. 
      The data is sampled using TABLESAMPLE SYSTEM (1 PERCENT) when in development mode. This is the only way to avoid high data processing costs.
      The latitude and longitude filters ensure that only occurrences within the specified range are included. 
    columns:
      - name: species
        description: "The species of the occurrence. This field is required and must not be null."
        tests:
          - not_null
      - name: individualcount
        description: "Count of individuals for the species. This field is required and must not be null."
        tests:
          - not_null
      - name: geography
        description: "The geographical location of the occurrence. This field is required and must not be null."
        tests:
          - not_null
      - name: eventdate
        description: "The date of the occurrence. This field is required and must not be null."
        tests:
          - not_null
      - name: source
        description: "The source of the occurrence. This field is required and must not be null."
        tests:
          - not_null
          - accepted_values:
              values: ['GBIF']

  - name: stg_obis_occurences
    description: |
      OBIS (Ocean Biogeographic Information System) is a global open-access data and information clearing-house on marine biodiversity. 
      It retrieves information about the species, individual count, event date, geographical location, and source from the `marine_data.obis_table` table.
      Which represents fresh parquet file from https://obis.org/.
      The `geography` column is derived from the `decimalLongitude` and `decimalLatitude` columns using the `ST_GEOGPOINT` function. 
      The data is limited to 100 when in development mode. This is the only way to avoid high data processing costs.
      The latitude and longitude filters ensure that only occurrences within the specified range are included.
    columns:
      - name: species
        description: "The species of the occurrence. This field is required and must not be null."
        tests:
          - not_null
      - name: individualcount
        description: "Count of individuals for the species. This field is required and must not be null."
        tests:
          - not_null
      - name: geography
        description: "The geographical location of the occurrence. This field is required and must not be null."
        tests:
          - not_null
      - name: eventdate
        description: "The date of the occurrence. This field is required and must not be null."
        tests:
          - not_null
      - name: source
        description: "The source of the occurrence. This field is required and must not be null."
        tests:
          - not_null
          - accepted_values:
              values: ['OBIS']

  - name: stg_reef_check_occurences
    description: |
      Reef Check foundation https://www.reefcheck.org/ is a community science project that collects data on the health and status of coral reefs worldwide. 
      The `geography` column is derived from the `longitude` and `latitude` columns using the `ST_GEOGPOINT` function. 
      The data is limited to 100 when in development mode. This is the only way to avoid high data processing costs.
      The latitude and longitude filters ensure that only occurrences within the specified range are included.
    columns:
      - name: species
        description: "The species of the occurrence. This field is required and must not be null."
        tests:
          - not_null
      - name: individualcount
        description: "Count of individuals for the species. This field is required and must not be null."
        tests:
          - not_null
      - name: geography
        description: "The geographical location of the occurrence. This field is required and must not be null."
        tests:
          - not_null
      - name: eventdate
        description: "The date of the occurrence. This field is required and must not be null."
        tests:
          - not_null
      - name: source
        description: "The source of the occurrence. This field is required and must not be null."
        tests:
          - not_null
          - accepted_values:
              values: ['REEF_CHECK']