
name: 'divesites_data'
version: '1.0.0'
config-version: 2

profile: 'divesites_data_bq'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  divesites_data:
      seabed:
          description: 'This model represents staged external tables from the several sources.'
          materialized: view
      coral:
          description: 'This model represents converted data from the staged sources to provide occurence reference tables.'
          materialized: table
      reef:
          description: 'Final aggregated tables for the divesites data.'
          materialized: table