
version: 2

sources:
 - name: invasive_species_source
   tables:
     - name: invasive_species_table
       location: 'gs://marine_data_412615/invasive_species.parquet/*'
       options:
         format: parquet
         allow_jagged_rows: true
         allow_quoted_newlines: true

models:
  - name: stg_local_data
    description: "A starter dbt model"